---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: firstdeployment
  labels:
     name: firstdeployment
  annotations:
    kubernetes.io/change-cause: "version update" 
spec:
  replicas: 4 
  selector:
    matchExpressions:
      - key: app
        operator: In
        values:
          - myapp1
          - myapp2
  template:
    metadata:
      name: pod
      labels:
        app: myapp1
    spec:
      containers:
        - name: container
          image: coolgourav147/nginx-custom

