---
apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: firstrs
  labels:
     app: myapp1 
spec:
  replicas: 2
  selector:
    matchLabels:
      app: myapp1
  template:
    metadata:
      name: pod
      labels:
        app: myapp1
    spec:
      containers:
        - name: container
          image: coolgourav147/nginx-custom
